# coding: utf-8

"""
    Video Insights

    The Video Insights API endpoint

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from videoinsights_client.models.media_file import MediaFile

class MediaFileList(BaseModel):
    """
    MediaFileList
    """
    files: conlist(MediaFile) = Field(...)
    has_more_pages: StrictBool = Field(...)
    max_pages: StrictInt = Field(...)
    page: StrictInt = Field(...)
    user: StrictStr = Field(...)
    __properties = ["files", "has_more_pages", "max_pages", "page", "user"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MediaFileList:
        """Create an instance of MediaFileList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item in self.files:
                if _item:
                    _items.append(_item.to_dict())
            _dict['files'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MediaFileList:
        """Create an instance of MediaFileList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MediaFileList.parse_obj(obj)

        _obj = MediaFileList.parse_obj({
            "files": [MediaFile.from_dict(_item) for _item in obj.get("files")] if obj.get("files") is not None else None,
            "has_more_pages": obj.get("has_more_pages"),
            "max_pages": obj.get("max_pages"),
            "page": obj.get("page"),
            "user": obj.get("user")
        })
        return _obj


