# coding: utf-8

"""
    Video Insights

    The Video Insights API endpoint

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ModeEnum(str, Enum):
    """
    * `NORMAL` - NORMAL * `FRAME_BY_FRAME` - FRAME_BY_FRAME
    """

    """
    allowed enum values
    """
    NORMAL = 'NORMAL'
    FRAME_BY_FRAME = 'FRAME_BY_FRAME'

    @classmethod
    def from_json(cls, json_str: str) -> ModeEnum:
        """Create an instance of ModeEnum from a JSON string"""
        return ModeEnum(json.loads(json_str))


