# coding: utf-8

"""
    Video Insights

    The Video Insights API endpoint

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt

class YoutubeStatistics(BaseModel):
    """
    YoutubeStatistics
    """
    comment_count: StrictInt = Field(default=..., alias="commentCount")
    favorite_count: StrictInt = Field(default=..., alias="favoriteCount")
    like_count: StrictInt = Field(default=..., alias="likeCount")
    view_count: StrictInt = Field(default=..., alias="viewCount")
    __properties = ["commentCount", "favoriteCount", "likeCount", "viewCount"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> YoutubeStatistics:
        """Create an instance of YoutubeStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> YoutubeStatistics:
        """Create an instance of YoutubeStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return YoutubeStatistics.parse_obj(obj)

        _obj = YoutubeStatistics.parse_obj({
            "comment_count": obj.get("commentCount"),
            "favorite_count": obj.get("favoriteCount"),
            "like_count": obj.get("likeCount"),
            "view_count": obj.get("viewCount")
        })
        return _obj


